### PR TITLE
Intel idle add GNR support and C6 fix

### PR DESCRIPTION
**Pull request by jiayingbao**
backport intel_idle support for GNR.
backport intel_idle fix for C6 enable/disable status.

test:
test passed and function ok.

### CODE REVIEW

**Comment by xiejingf** [comment]
The title is wrong, it is GNR.

**Comment by cuiyunhui** [comment]
gnr or grn ? @jiayingbao

**Comment by jiayingbao** [comment]
> gnr or grn ? @jiayingbao

sorry, typo. GNR

**Comment by qiruibd** [comment]
@jiayingbao Have you actually verified based on this code repository?

**Comment by qiruibd** [comment]
LGTM

**Comment by aaronlu** [comment]
LGTM

**Comment by jiayingbao** [comment]
seems many package is missed on test device.
Makefile.config:597: No sys/sdt.h found, no SDT events are defined, please install systemtap-sdt-devel or systemtap-sdt-dev
Makefile.config:978: No libzstd found, disables trace compression, please install libzstd-dev[el] and/or set LIBZSTD_DIR
Makefile.config:989: No libcap found, disables capability support, please install libcap-devel/libcap-dev
Makefile.config:1061: No libbabeltrace found, disables 'perf data' CTF format support, please install libbabeltrace-dev[el]/libbabeltrace-ctf-dev
Makefile.config:1095: No alternatives command found, you need to set JDIR= to point to the root of your Java directory
Makefile.config:1126: libpfm4 not found, disables libpfm4 support. Please install libpfm4-dev
Makefile.config:1144: *** ERROR: libtraceevent is missing. Please install libtraceevent-dev/libtraceevent-devel or build with NO_LIBTRACEEVENT=1.  Stop.
make[6]: *** [Makefile.perf:242: sub-make] Error 2
make[5]: *** [Makefile:113: install] Error 2
make[4]: *** [Makefile:2044: run-command] Error 2

**Comment by aaronlu** [comment]
I don't know what happened on the bot but I can confirm it builds without any issues at my side.

**Pull request merged**
